# Generated by Django 5.2.3 on 2025-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=':3', max_length=255),
            preserve_default=False,
        ),
    ]
