# Generated by Django 5.2.3 on 2025-06-19 17:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.JSONField(default=tasks.models.default_task, verbose_name='tasks'),
        ),
    ]
