# Generated by Django 5.2.3 on 2025-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='longestLivingTask',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='totalNumTasks',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
