# Generated by Django 5.2.3 on 2025-06-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_user_longestlivingtask_user_totalnumtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='longestLivingTaskTime',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='longestLivingTask',
            field=models.JSONField(),
        ),
    ]
