# Generated by Django 5.2.3 on 2025-06-22 22:39

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_user_longestlivingtasktime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='longestLivingTask',
            field=models.JSONField(default=tasks.models.default_task, verbose_name='lltask'),
        ),
    ]
